### ISSUE TITLE
How do I use this in an Ionic 2 app?

### ISSUE THREAD

**Issue by jourdan-jobox** [mnill/cordova-custom-keyboard#3]
I did the initial set up to add the plugin to my Ionic 2 app; but I'm at a loss of how to use the CustomKeyboard. 

When I try to use `CustomKeyboard` in one of my typescript files, I get a `Cannot find name 'CustomKeyboard'`. And that's fine, but now I think the issue is that I need to `import` it into my typescript file. 

This is where I'm stuck. How do I import this plugin into my Typescript file? I tried to do:

```
import { CustomKeyboard } from '/plugins/ru.appsm.customkeyboard/www/customkeyboard.js'
```

I also tried it without `.js` at the end. The error I'm getting is `Cannot find module '/plugins ...'`

Any help would be great!

**Comment by mnill** [comment]
Sorry, I am not tried typescript.

Try window.CustomKeyboard?

**Comment by jourdan-jobox** [comment]
I didn't use window.CustomKeyboard but after getting better at Typescript, I figured out how to use this with Ionic 2. I'm happy to explain briefly through here or contribute somehow to a wiki or something to explain!
